services:
    app:
      image: employee-management-be-image:latest
      restart: on-failure
      ports:
        - 3000:3000
      env_file:
        - ./.env
      depends_on:
        database:
          condition: service_healthy
    redis:
      image: redis
    database:
        image: mysql
        restart: always
        healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10

        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: 'password123'
          MYSQL_DATABASE: employe_db
    db-migrate:
      image: employee-management-be-image:latest
      env_file:
        - ./.env
      depends_on:
        database:
          condition: service_healthy
      command: ["sh", "-c", "npx prisma db push && npm run runner src/seed/seedAdmin.ts"]
        