openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: API documentation
servers:
  - url: http://localhost:3000
    description: Local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /api/user/login:
    post:
      summary: User login
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email of the user
                  example: "anup@gmail.com"
                password:
                  type: string
                  description: Password for the user account
                  example: "qwert123"
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  message:
                    type: string
                    description: Success message
                    example: "User logged in successfully"
        422:
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                    example: "Validation failed"
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                        example: "Invalid credentials"

  /api/employee/add:
    post:
      summary: Add a new employee
      tags:
        - Employee
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Job title of the employee
                  example: "Software Engineer"
                yearly_salary:
                  type: number
                  description: Yearly salary of the employee
                  example: 60000
                address:
                  type: string
                  description: Address of the employee
                  example: "Lalitpur"
                email:
                  type: string
                  description: Email of the employee
                  example: "sagar@gmail.com"
                name:
                  type: string
                  description: Name of the employee
                  example: "Sagar Dahal"
                phone:
                  type: string
                  description: Phone number of the employee
                  example: "9861311546"
                password:
                  type: string
                  description: Password for the employee account
                  example: "password123"
      responses:
        201:
          description: Employee and user created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  employee:
                    type: object
                    description: The created employee objects
                  user:
                    type: object
                    description: The created user object
        500:
          description: Failed to add employee
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                    example: "Failed to add employee"

  /api/employee/{id}:
      patch:
        summary: Update an employee
        tags:
          - Employee
        security:
          - bearerAuth: []
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID of the employee to update
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: Title of the employee
                    example: "QA Engineer"
                  yearly_salary:
                    type: number
                    description: Yearly salary of the employee
                    example: 30000
                  address:
                    type: string
                    description: Address of the employee
                    example: "Ktm"
                  email:
                    type: string
                    description: Email address of the employee
                    example: "example@example.com"
                  name:
                    type: string
                    description: Name of the employee
                    example: "Example"
                  phone:
                    type: string
                    description: Phone number of the employee
                    example: "9832218181"
        responses:
          '201':
            description: Employee updated successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    updatedEmployee:
                      type: object
                      description: The updated employee objects
                    updatedUser:
                      type: object
                      description: The updated user object
          '500':
            description: Failed to update employee
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      description: Error message
                      
      get:
        summary: Fetch an employee by ID
        tags:
          - Employee
        security:
          - bearerAuth: []
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID of the employee to fetch
        responses:
          '200':
            description: Employee fetched successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID of the employee
                      example: 1
                    title:
                      type: string
                      description: Job title of the employee
                      example: "Software Engineer"
                    yearly_salary:
                      type: number
                      description: Yearly salary of the employee
                      example: 60000
                    address:
                      type: string
                      description: Address of the employee
                      example: "Lalitpur"
                    email:
                      type: string
                      description: Email of the employee
                      example: "sagar@gmail.com"
                    name:
                      type: string
                      description: Name of the employee
                      example: "Sagar Dahal"
                    phone:
                      type: string
                      description: Phone number of the employee
                      example: "9861311546"
          '500':
            description: Failed to fetch employee
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      description: Error message
                      example: "Failed to fetch employee"

      delete:
        summary: Delete an employee
        tags:
          - Employee
        security:
          - bearerAuth: []
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
            description: ID of the employee to delete
        responses:
          '204':
            description: Employee deleted successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    msg:
                      type: string
                      description: Success message
                      example: "Employee deleted successfully"
          '500':
            description: Failed to delete employee
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      description: Error message
                      example: "Failed to delete employee"

                    
  /api/employeer/add:
    post:
      summary: Add a new employeer
      tags:
        - Employeer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: Address of the employee
                  example: "Lalitpur"
                email:
                  type: string
                  description: Email of the employee
                  example: "ratan@gmail.com"
                name:
                  type: string
                  description: Name of the employee
                  example: "Ratan Dahal"
                phone:
                  type: string
                  description: Phone number of the employee
                  example: "9861310546"
                password:
                  type: string
                  description: Password for the employee account
                  example: "password@123"
      responses:
        201:
          description: Employeer and user created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  employeer:
                    type: object
                    description: The created employeer object
                  user:
                    type: object
                    description: The created user object
        500:
          description: Failed to add employeer
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                    example: "Failed to add employeer"
